services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME} 
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./mongo_data:/data
    ports:
      - 27017:27017
  mongo-express:
    container_name: mongo_express
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_ADMIN_USERNAME} 
      ME_CONFIG_BASICAUTH_PASSWORD:  ${MONGO_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      # ME_CONFIG_MONGODB_URL: ${MONGO_URL}
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
